#!/usr/bin/env bash
# Update and upgrade the system
apt update && apt upgrade -y

# Install HAProxy
apt install haproxy -y

# Create a backup of the default HAProxy configuration file
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Replace the default HAProxy configuration with a new one
cat << EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log local0.
    daemon

defaults
    mode    http
    option  httplog
    option  dontlognull

frontend  web
    bind *:80
    option  httplog
    default_backend webservers

backend webservers
    balance roundrobin
    server 248562-web-01 18.209.233.65:80 check
    server 248562-web-02 35.175.65.54:80 check
EOF

# Restart HAProxy
systemctl restart haproxy

# Enable HAProxy at boot time
systemctl enable haproxy

# Check if web servers are present in the configuration
grep -E "web-01|web-02" /etc/haproxy/haproxy.cfg
