#!/usr/bin/env bash
# Bash script that uses ssh to connect to your server using the private key
# Connect to the server using single-character flags
ssh -i ~/.ssh/school ubuntu@18.209.223.65

# Wait for the user to exit the session
echo "Connection to 8.8.8.8 closed."
